name: "Test entangler build"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        nixPath:
          - artiq-full=https://nixbld.m-labs.hk/channel/custom/artiq/full/artiq-full:nixpkgs=channel:nixos-21.05
          - artiq-full=https://nixbld.m-labs.hk/channel/custom/artiq/full/artiq-full:nixpkgs=channel:nixos-21.11
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command
          substituters = https://cache.nixos.org https://nixbld.m-labs.hk
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixbld.m-labs.hk-1:5aSRVA5b320xbNvu30tqxVPXpld73bhtOeH6uAjRyHc=
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Build Nix Package
      env:
        # Allow building unfree packages & unsupported systems for CI purposes
        NIXPKGS_ALLOW_UNFREE: 1
        NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
      run: nix-build ./nix/default.nix
